create extension if not exists pgcrypto;

create table if not exists users (
 telegram_id bigint primary key,
 username text,
 first_name text,
 last_name text,
 balance numeric(12,2) not null default 0,
 referred_by bigint,
 referral_code text generated always as ('ref_' || telegram_id::text) stored,
 created_at timestamptz default now()
);

create table if not exists tasks (
 id uuid primary key default gen_random_uuid(),
 title text not null,
 description text,
 reward numeric(12,2) not null default 0,
 duration_seconds int not null default 10,
 active boolean not null default true,
 created_at timestamptz default now()
);

create table if not exists task_claims (
 id uuid primary key default gen_random_uuid(),
 task_id uuid references tasks(id) on delete cascade,
 telegram_id bigint references users(telegram_id) on delete cascade,
 created_at timestamptz default now(),
 unique(task_id,telegram_id)
);

create table if not exists withdrawals (
 id bigint generated by default as identity primary key,
 telegram_id bigint references users(telegram_id),
 method text not null,
 address text not null,
 amount numeric(12,2) not null,
 status text not null default 'pending',
 created_at timestamptz default now()
);

create table if not exists settings (
 key text primary key,
 value text not null
);

insert into settings(key,value) values
 ('referral_commission','5'),
 ('min_withdraw','50'),
 ('spin_reward','1'),
 ('video_reward','1')
on conflict(key) do nothing;

create table if not exists ad_slots (
 key text primary key,
 code text not null default '',
 active boolean not null default true
);

insert into ad_slots(key) values ('adsterra'),('socialbar'),('popunder')
on conflict(key) do nothing;

create or replace function credit_balance(p_telegram_id bigint,p_amount numeric,p_reason text)
returns void language plpgsql security definer as $$
begin
 update users set balance=balance+p_amount where telegram_id=p_telegram_id;
end $$;

create or replace function apply_referral_signup(p_referrer bigint,p_new_user bigint,p_commission numeric)
returns void language plpgsql security definer as $$
begin
 -- Signup referral is recorded. Commission payout can be configured separately.
 update users set referred_by=p_referrer where telegram_id=p_new_user;
end $$;
